### ISSUE TITLE
Find a way to consolidate testing

### ISSUE THREAD

**Issue by brettvanderwerff** [brettvanderwerff/Flaskerizer#17]
Right now the user needs to invoke 3 different commands to cover all the tests. It would be great if there was a way we could consolidate these in some way so that the user only need to invoke one command to test the program. I don't know enough about testing to say whether the 3 different test files can be combined into one test file or if we need another script that automatically runs 3 different test files we have now. I'm guessing the first option is the correct one, but it will require some googling to see how other people do it.

**Comment by makkoncept** [comment]
pull request #20 addresses this issue
