### ISSUE TITLE
prompt user to select which files they want to go in static and templates folder through a pop up menu

### ISSUE THREAD

**Issue by brettvanderwerff** [brettvanderwerff/Flaskerizer#22]
This is just something I thought about, and might be something we can consider when the project is further along, but it might be an interesting idea to have a popup menu appear when the user run to program prompting them specifically which folder they want migrated to the static folder and which HTML files they want migrated to the templates folder with tkinter or something like that. I don't know how feasible this is but it might solve two problems:

1. we dont always know the path to static folder contents and html files in the source bootstrap template folder, right now the program just makes assumptions about where that stuff is.

2. It could relieve some of the issues there are with redundant HTML files in different locations within the source bootstrap templates, which sometimes happens. The user would just pick the file they know is the right one.

**Comment by etiontdn** [comment]
I want to give a try if no one is working at this at the moment,
just some questions.
Is it only to select the HTML STATIC JS folders?

**Comment by brettvanderwerff** [comment]
Hi etiontdn, welcome to the flaskerizer project!

 Right now we have the user pointing to the HTML, static, and js folder content by pointing to the full path of these manually in the config.py file.  This feature was developed after this issue was raised and seems like a good lightweight way to get the unambiguous paths to these directories at the time, I would like to retain this functionality as the default for the user, but developing a gui prompt alongside this seems like a great idea and we have obviously been thinking about it. If you are interested in making a gui pop up for selecting these directories for this, I think that would be great. Because we know the way we do it now works and seems to work well, my preference would be to make the gui option something the user has available but need to uncomment to engage. However, if in practice  the gui is outperforming our current standard/is more popular then we will make the gui popup default and have the manual path pointing an option the user needs to uncomment to use. I'd love to hear anyone's input on this though.

I don't know a ton about the gui libraries. I can see you have worked on the prog-o-meter and I know they use tkinter but what I don't know is if tkinter is the best for us or not. You'll have to weigh available  the options and make a decision.  My preference would be something that has good functionality, is lightweight (fast not a lot of code), and works on multiple platforms (most of our development right now has focused on being compatible with ubuntu and windows)

I really appreciate that you took the time to look at this project. No one has this issue right now and I would be happy to block it off for you if you would like it :). Let me know if you have any questions.

**Comment by etiontdn** [comment]
Thanks, i think Tkinter isnt a Bad idea, because it comes by default with almost all python installs and it is relatively simple to make and wont take even 50 lines since it looks like this is a really simple thing to do
As of the optional thing, i think i can make a separate file or a class that can be called optionally.
another questions not totally relationed to this:
1. Is this repository python 2 and python 3 compatible?
2. About the code style are there any thing i need to have in mind? like tabs or spaces, PEP8, etc.
3. Any type of Docstrings or comments needed?

I will give a try at this 😄

**Comment by brettvanderwerff** [comment]
@etiontdn see my last comment, but this issue is yours by the way.

**Comment by etiontdn** [comment]
Thanks, i'm going to start working on it then!

**Comment by brettvanderwerff** [comment]
With #54 we will need to change the GUI a bit, but for now I am closing this issue. I will open a new issue if the GUI needs work
