### ISSUE TITLE
Feature: Let the user put the destination path

### ISSUE THREAD

**Issue by makkoncept** [brettvanderwerff/Flaskerizer#30]
Right now the templates and the static folders and `app.py` are made in the same directory as the application . The user then moves it to the Flask project directory as the present one is very cluttered and the  user will not want to continue the project in the same directory and if the user decides to continue then he/she has to delete all the not required files, make a new requirements.txt for the flask project etc.
What can be done is that user also have to enter the location of the flask project in the `config.py` file and instead of making the folders  in the same directory, the folders are made at that location.

**Comment by brettvanderwerff** [comment]
@makkoncept Thats a great idea, its pretty straight forward to code also. Try and have issue titles be a bit more specific to the feature you are suggesting. Tag this as you see fit (let me know if you cant).  "good first issue" is always a great tag for things like this as this would be a good intro python problem.

**Comment by brettvanderwerff** [comment]
@makkoncept I started thinking about this more, part of the issue with doing this would be that if we write the flask files outside the working directory the user might not be able to test their changes right away, especially if they are working in a virtual environment they would have to go set up the virtual environment wherever the files are written to before they could run it. This might require some thought, I'm not sure what the answer is yet and am open to suggestions. The working directory is getting very cluttered, part of that is because the project grew so much since I originally started it. Refactoring the project tree might be a good issue to raise. I can see some possible fixes right away: consolidate examples to one folder, see if we can get all the testing files together in one folder, etc.

**Comment by makkoncept** [comment]
Sooner or later the user will want to migrate the flask project away as all the other files , be it of tests or template examples are not part of its project, its part of Flaskerizer . Flask project grows out to be a large chunk of files.
I think we can do two things. Either put templates, static and app.py in a folder name `Flask project` in the same directory as Flaskerizer, user can then cd into it but he/she still has to create a new virtual environment as this project is different from Flaskerizer and new environment is still needed and when the project is complete , move the whole project to a new place. **Or** give the user the privilege to set the destination directory,if they want to run tests, the user can put the Flaskerizer directory path at the destination . Providing the choice , where to put your project can be a good thing for the user, he/she is free to decide. 
About putting the tags, it is not showing the option to me . You can put the desired tags.

**Comment by brettvanderwerff** [comment]
@makkoncept I want to leave this open to give people a chance to make input on the issue. I don't know what the right answer is yet, those are the two ideas I had too.

**Comment by brettvanderwerff** [comment]
@makkoncept I think just a configuration setting that points to a path the user would like to write their "clean" app to would be great as a start we could even leave it commented out so the user can consider this functionality optional.

**Comment by makkoncept** [comment]
yeah, i think this would be nice. This could be a good first issue, or i can take it if its urgent?

**Comment by brettvanderwerff** [comment]
@makkoncept I labeled it as good first issue, we'll see if someone takes it in the next few days, but I would say if you would like to do it go ahead and give it a go. I'll leave it open for a bit if no one takes it, I will do the PR. Thanks for commenting!

**Comment by makkoncept** [comment]
Yeah, we can leave it open for few days. There is always room for new contributors

**Comment by brettvanderwerff** [comment]
I'm going to take this issue and work on a solution, it will help clean the repo too, which I have been trying to make progress towards recently with PR #45.

**Comment by brettvanderwerff** [comment]
In PR #47  I changed the project to write the Flask app in a designated folder in the repo. This keeps it nice and clean and separated from the Flaskerizer source code. This issue will be closed.
