### ISSUE TITLE
Alstar bootstrap template from bootstrapmade.com does not work (need to parse javascript files)

### ISSUE THREAD

**Issue by brettvanderwerff** [brettvanderwerff/Flaskerizer#31]
It seems like most templates from bootstrapmade.com work with flaskerizer, however alstar does not work:

https://bootstrapmade.com/alstar-free-parallax-bootstrap-template/

I get the following error in the terminal when trying to launch the flaskerized version of alstar:

`/img/bgslides/1.jpg HTTP/1.1" 404 -`

It would be good if someone can confirm this issue.

The only place I see a reference to this path is in the exploded directory `/static/js/custom.js`

I don't know if these means we may need to parse javascript for links to fix in addition to HTML, maybe someone with front end experience can chime in?

**Comment by brettvanderwerff** [comment]
OK I looked into this, its the javascript that needs to be fixed. 

It works beautifully if you manually change 

`"img/bgslides/1.jpg"` in custom.js to

`"static/img/bgslides/1.jpg"`



We need a parse javascript method in StructureDirectory that will make these changes automatically.

**Comment by brettvanderwerff** [comment]
I'm taking this issue

**Comment by anusonibangalore** [comment]
Thanks for sharing, this is a fantastic article post.Really looking forward to read more. Really Great.
visit my website - [anusoni.com](https://anusoni.com/)
