### ISSUE TITLE
Awesome work

### ISSUE THREAD

**Issue by kimthostrup** [brettvanderwerff/Flaskerizer#37]
No issues, I just wanted to say that you did a awesome job of creating this tool. 

Thanks.

**Comment by brettvanderwerff** [comment]
@kimthostrup Thanks! There was help from others, it was really a team effort and it is still being polished. Do you work with Flask? If you do and if you use Flaskerizer it would be awesome if you raise an issue for any problems you come across. There are things that we know don't work, but we are moving forward and patching as we go!

**Comment by kimthostrup** [comment]
@brettvanderwerff I only use Flask on a hobby basis, but I will let you know if I find any issues.
