### ISSUE TITLE
Refactor parse_links

### ISSUE THREAD

**Issue by brettvanderwerff** [brettvanderwerff/Flaskerizer#57]
the parse_links method of the StructureDirectory class in the structure_directory.py module is pretty messy, refactoring it for readability, possible breaking it down into additional methods if needed  is a good issue for someone looking to get into open source. 

I'll eat this one if no one else is up for it, I wrote that method in the first place, but I think it would be a good entry issue for a newcomer, so I am posting it.

**Comment by avnish98** [comment]
I would like to work on this

**Comment by brettvanderwerff** [comment]
That would be great I certainly could use help on it

**Comment by avnish98** [comment]
Thanks, I will tell you when I am close

**Comment by brettvanderwerff** [comment]
@avnish98 Unfortunately because of time issues I am not able to review this at that detail. I would recommend using the print function after each condition to  get a feel for what they are changing.  I know its tough because it a messy function, but coming up with a way to address that is part of the PR. I appreciate that you took the issue and hope it goes well. Please let me know when you ready to merge and I will take a look at the code. Thank you!

**Comment by brettvanderwerff** [comment]
Addressesed and closed with pr #73
