### ISSUE TITLE
Docker for deployment 

### ISSUE THREAD

**Issue by brettvanderwerff** [brettvanderwerff/Flaskerizer#6]
Unlike the other issues, this is might not be a good first issue, but integrating Docker into the Flaskerizer might be a way to make the automated website build performed by Flaskerizer even more deployment ready. I have some but overall a very limited amount of experience with Docker, does anyone more experienced with Docker have input on this?

**Comment by jmbriody** [comment]
Just sent you a pull request with the docker stuff and some minor changes.
