### ISSUE TITLE
Allow shorter command line argument aliases 

### ISSUE THREAD

**Issue by brettvanderwerff** [brettvanderwerff/Flaskerizer#74]
Right now the flags for command line arguments are very long and easy to make mistakes typing/hard to remember (i.e. --top-level-path). It would be god to incorporate a one or two letter alias for each flag that the user could use. Maybe top level path could be -TL or -T or something like that. We could still allow the more verbose flags, these shorter flags would just be an optional abbreviation the user could opt for. I believe these are called aliases in argparse and I think they are very easy to implement. I am marking it as high priority because we have a lot of required arguments and its not fun to type them all out. I will take this if no one wants it,but I will leave it open for a while to let newcomers grab it.

https://docs.python.org/3/library/argparse.html

**Comment by brettvanderwerff** [comment]
@avnish98 Great! I made some comments on you PR #73.

**Comment by avnish98** [comment]
@brettvanderwerff Thanks I will start working on shortening the aliases by tomorrow

**Comment by brettvanderwerff** [comment]
Closed with PR #77
