### ISSUE TITLE
Ubuntu 18.04 and python 3.6.5 bug where extra characters are added to links

### ISSUE THREAD

**Issue by brettvanderwerff** [brettvanderwerff/Flaskerizer#75]
I am having a problem with Flaskerizer of Ubuntu 18.04 with Python 3.6.5

How to recreate : 

When running Flaskerizer in small app structure against the template: https://startbootstrap.com/template-overviews/one-page-wonder/ (although I don't think the template matters) I get link errors when trying to launch the flask app 

127.0.0.1 - - [03/Sep/2018 09:59:31] "GET /vstatic/css/000027bootstrap.min.css HTTP/1.1" 404 -
127.0.0.1 - - [03/Sep/2018 09:59:31] "GET /cstatic/css/000012one-page-wonder.min.css HTTP/1.1" 404 -
127.0.0.1 - - [03/Sep/2018 09:59:31] "GET /vstatic/js/000026jquery.min.js HTTP/1.1" 404 -
127.0.0.1 - - [03/Sep/2018 09:59:31] "GET /vstatic/js/000036bootstrap.bundle.min.js HTTP/1.1" 404 -
127.0.0.1 - - [03/Sep/2018 09:59:31] "GET /istatic/img/00001103.jpg HTTP/1.1" 404 -
127.0.0.1 - - [03/Sep/2018 09:59:31] "GET /istatic/img/00000902.jpg HTTP/1.1" 404 -
127.0.0.1 - - [03/Sep/2018 09:59:31] "GET /istatic/img/00001001.jpg HTTP/1.1" 404 -
127.0.0.1 - - [03/Sep/2018 09:59:31] "GET /vstatic/js/000036bootstrap.bundle.min.js HTTP/1.1" 404 -

For some reason Flaskerizer is tacking extra characters onto the beginning of folder names in these links. For example, the first broken link should be:

/static/js/000026jquery.min.js 

NOT

 /vstatic/js/000026jquery.min.js

This isn't an issue on windows 10 and did not used to be an issue on ubuntu, I think this is a new bug either specific to ubuntu 18.04 or python 3.6.5 

Could someone at least confirm this is an issue for them and not specific to me?

I am open to fixes as well. I have not figured this one out yet.

**Comment by brettvanderwerff** [comment]
I have tried this on two different Ubuntu 18.04 machine, I believe this is a real problem and not just me. Because many people that will use this program are on ubuntu, this is a high priority issue

**Comment by brettvanderwerff** [comment]
@avnish98 I think made progress on figuring out  what the issue is it. I think it has to do less with ubuntu/python and more  with whether the person leaves a trailing / on the paths they pass as arguments for templates path, top level path etc. I think checking whether the user leaves a trailing slash to the paths they give and then adding one if they didn't would solve this.  The endswith string method would be good for this. I will try and implement this

**Comment by avnish98** [comment]
@brettvanderwerff I agree with you because I tested the template on my machine and I didn't find any such issue
![screenshot from 2018-09-04 00-21-10](https://user-images.githubusercontent.com/29746858/44999130-bb00f900-afd8-11e8-986f-e70caf235dcb.png)

**Comment by brettvanderwerff** [comment]
@avnish98 Thanks for checking that I am going to make a quick fix for this right now.

**Comment by brettvanderwerff** [comment]
Resolved with #76
