### ISSUE TITLE
Make a config.py file to store the bootstrap template directory

### ISSUE THREAD

**Issue by brettvanderwerff** [brettvanderwerff/Flaskerizer#8]
Right now the user has to open flaskerizer.py and pass their directory path to the structure_directory_object. It would be nice to have a separate config file that the user would just open and put their configurations like directory paths in there rather than having to dig through python scripts.

See link:

https://hackernoon.com/4-ways-to-manage-the-configuration-in-python-4623049e841b

**Comment by makkoncept** [comment]
Can you clarify what all configurations will be there in `config.py` or only directory path need to be added as of now . I would like to work on this issue.
 Also issue #12 will be resolved in this issue as the directory attribute  of  `structure_directory.py` will be used.

**Comment by brettvanderwerff** [comment]
@makkoncept Just a quick note, I might not see comments unless you tag me by tying the @ sign then you should see a dropdown menu for my name. For now its only the directory path to the bootstrap template, but its good to have a config file for the user, its cleaner for them when setting their configurations. If the project grows it will be nice to have the config file then we can just dump any new configurations directly into the config file. Note that the readme will have to be updated too. No one else is working on this issue it is all yours! Let me know if you have any other questions and thanks again.
